### ISSUE TITLE
Caelus flight doesn't trigger by double tap

### ISSUE THREAD

**Issue by SwagRabbit** [TheIllusiveC4/Caelus#14]
#### Versions (Be specific, do not write "latest"):
* Caelus: 1.15.2-2.0-beta3
* Forge/Fabric:1.15.2-31.2.45
#### Steps to Reproduce:
1.Stand on ground.
2.Equip Elytra.
3.Double tap jump key.

Crash Log: N/A

Please could you change the implementation to replicate the vanilla behavior.

**Comment by TheIllusiveC4** [comment]
Using your exact same versions, I cannot replicate your issue. Double-tapping the jump key works fine for me to trigger the Elytra flight.

**Comment by Homura14** [comment]
caelus-FORGE-1.15.2-2.0-beta3
curios-FORGE-1.15.2-2.0.2.6
curiouselytra-FORGE-1.15.2-2.0

- I can confirm **beta 3 1.15.2** is broken as in double tap jump won't trigger elytra.

caelus-FORGE-1.16.1-2.0-beta4
caelus-FORGE-1.16.1-2.0-beta5
caelus-FORGE-1.16.1-2.0-beta6
curios_FORGE-1.16.1-3.0.0.2
curiouselytra-FORGE-1.16.1-3.0

- Tested **beta 4 1.16.1**, **beta 5 1.16.1** with same results as above. **beta 6 1.16.1** with mixins works as expected.

**Comment by TheIllusiveC4** [comment]
This was caused by a change in Forge that was incompatible with this mod's pre-Mixins setup. I've updated the 1.15 build with a quick workaround.
