### ISSUE TITLE
Caelus Flight Attribute Lacks a Translated Name

### ISSUE THREAD

**Issue by CammiePone** [TheIllusiveC4/Caelus#16]
#### Versions (Be specific, do not write "latest"):
* Caelus: 0.0.14-1.16.4
* Fabric: 0.25.1+build.416-1.16
#### Observed Behavior:
Game tries to translate `caelus.elytra_flight` instead of `attribute.name.generic.caelus.flight`, leading to an untranslated attribute on items.
![image](https://user-images.githubusercontent.com/16853086/101447187-b4b60180-38f2-11eb-97cc-08d6aba74c14.png)
#### Expected Behavior:
The translation file to have the correct translation key. My guess is Forge does something funky with attributes, and it wasn't caught in porting over to Fabric.
#### Steps to Reproduce:
1. Add the Caelus flight attribute to an item
2. Run the game
3. See the untranslated name

**Comment by TheIllusiveC4** [comment]
I have no idea how I missed this. Anyways, thanks for the report, this should be fixed now in version 0.0.15-1.16.4.
