### ISSUE TITLE
Toggle Elytra - Using a keybinding, default 'v',  not work  and do not appear in the settings

### ISSUE THREAD

**Issue by Ashtar084** [TheIllusiveC4/Caelus#17]
Toggle Elytra - Using a keybinding, default 'v',  not work  and do not appear in the settings

#### Versions (Be specific, do not write "latest"):
* Caelus: 

caelus-forge-1.16.4-2.1.0.0

* Forge/Fabric:

 both.

#### Observed Behavior:

keybinding, default 'v',  not work  and do not appear in the settings

#### Steps to Reproduce: 
1.open world game to see
2.open config controls not appear
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
That feature was removed in 1.16. It's listed under "Pre-1.16 Features" on the project page. It will return as a separate mod when I have time to make it.
