### ISSUE TITLE
Crash during load with only import statement.

### ISSUE THREAD

**Issue by Amperthorpe** [TheIllusiveC4/Caelus#18]
#### Versions (Be specific, do not write "latest"):
* Caelus: 1.16.4-2.1.0.0
* Forge/Fabric: forge:1.16.4-35.1.15
#### Observed Behavior:
Below crash when attempting to run game. The only reference to Caelus in my code is an import statement.
This also happened with a fresh Forge example mod project.
#### Expected Behavior:
The API not crashing.
#### Steps to Reproduce:
1. Download and set up Forge MDK example mod.
2. Add Caelus and Maven to build.gradle following the instructions.
3. Add line "import top.theillusivec4.caelus.api.CaelusApi;" to ExampleMod.java
4. Build and launch game
5. Crash as below.

Crash Log: 
https://gist.github.com/Alleluid/32d3d8edce85485e487169d7669ec1c1

**Comment by TheIllusiveC4** [comment]
Because Caelus uses mixins, you need to set the `mixin.env.disableRefMap` JVM argument to true when working in a development environment. My apologies that this isn't reflected in documentation anywhere, I'll update the README to reflect this.

**Comment by Amperthorpe** [comment]
Ah, it's working now. Thank you.
