### ISSUE TITLE
Elytra model doesn't render on Armor Stands

### ISSUE THREAD

**Issue by Guardian259** [TheIllusiveC4/Caelus#21]
Elytras making use of `RenderElytraCallback` currently cannot render on Armorstands as `RenderElytraCallback` only has a listener for the `PlayerEntity` and does not include the `ArmorStandEntity`

Vanilla Elytras are fully capable of being displayed on Armorstands and as such an addition to the `RenderElytraCallback` event to allow for rendering on Armorstands will add both parity to the vanilla mechanics, as well as, offer more for modders to work with.

**Comment by TheIllusiveC4** [comment]
So I thought about how I could implement this smoothly, but I think I'll wait until I refactor some of the rendering for the 1.17 port. I don't want to risk breaking any current implementations and I'm not even sure I'm going to keep the callback/feature renderer in the future in favor of having consumers provide their own feature renderers and integrating with those.

In the meantime, to enable rendering on armor stands, implementations will just have to provide their own `ElytraFeatureRenderer` themselves.

**Comment by TheIllusiveC4** [comment]
As of 1.17, I've decided that rendering management is now outside the scope of Caelus in order to focus purely on functionality and minimize bloat. Implementations should provide their own renderers if necessary.
