### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by dx1r** [TheIllusiveC4/Caelus#24]
Game crashes when I add Caelus AND Optifine together in the mods folder, doesn't crash when I remove either one of them. This wasn't occurring like 2 months ago when I last played. I had both of them installed and no crashes happened.

Minecraft version: 1.16.5
Optifine version: 1.16.5 HD U G8 
Caelus version: 1.16.5 2.1.3.0 (Every version crashes from 2.1.2.2 to the latest one)

Crash Log: https://pastebin.com/raw/McdSSaBY

**Comment by TheIllusiveC4** [comment]
The crash log says you're trying to load Curious Elytra while Caelus is _not_ installed.
