### ISSUE TITLE
[Bug] [Forge]: compatibility issue with JEI + Create

### ISSUE THREAD

**Issue by Eario** [TheIllusiveC4/Caelus#27]
### Minecraft Version

1.18.1

### What happened?

When using this with Just Enough Items and Create, all recipes added by Create that are "non-standard" (not using vanilla crafting methods) are no longer visible within Just Enough Items.
(This happens on the 1.18.1 version, but as that is not presently an option in your bug report form it's getting filed under 1.17).

### How do you trigger this bug?

1. Install relevant version of minecraft forge.
2. Install mods: Caelus 3.0.0.1, Create 0.4a, Flywheel 0.4.2, JEI 1.0.47
3. Open Minecraft installation
4. Create new world
5. Open Inventory
6. In JEI, check the recipe for anything from Create that is NOT crafted in a crafting table, furnace, stonecutter, etc. (examples: flywheel, crushing wheel, precision mechanism).

### Loader

Forge

### Loader Version

Forge - version 39.0.5

### Mod Version

Caelus - 1.18.1-3.0.0.1

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this issue. Loading those mods together, I can see the recipes in JEI for the Flywheel and the Crushing Wheel just fine. They appear as they do normally. I'm not even sure how Caelus could cause this kind of issue to begin with.

Did you test this with _only_ those mods installed? If so, does the issue go away if you remove Caelus?
