### ISSUE TITLE
[Bug]: Spectral Elytra from Mana and Artifice doesn't function if Caelus is installed

### ISSUE THREAD

**Issue by Not-February** [TheIllusiveC4/Caelus#28]
### Minecraft Version

1.18.1

### What happened?

Mana and Artifice adds a midgame item called the Spectral Elytra which allegedly borrows vanilla elytra behavior while adding some unique traits of its own. Namely, it uses mana from the mod to propel you where you look as you fly and allows you to use it as a regular elytra while sneaking.

However, I am unable to get the Spectral Elytra to function as an elytra at *all* if Caelus happens to be installed alongside MNA. Regular elytras work as expected.

This appears to be a known incompatibility on MNA's end in their discord, yet I haven't seen anyone actually report this to you with useful information despite someone mentioning it on the Curseforge page comments in December 2021 as a warning to other users.

Since MNA is closed source, you may need to talk with its author to figure out exactly where the problem lies.

Other mods/versions installed while reproducing the issue:

- Mana and Artifice 1.7.0.5
- GeckoLib 3.0.11
- Curios API 5.0.6.2

### How do you trigger this bug?

1. Install the aforementioned mods and load into a world.
2. Run the commands /setmagiclevel 30, /setfaction fey_court, and /settier 4 to ensure you have a mana bar, faction, and tier for MNA that are adequate for using the item
3. Equip a Spectral Elytra from the creative menu to your chest slot
4. Notice the lack of being able to use it as an elytra

### Loader

Forge

### Loader Version

Forge 39.1.2

### Mod Version

Caelus 1.18-3.0.0.1

**Comment by TheIllusiveC4** [comment]
I see that you're using Caelus version 1.18-3.0.0.1. The latest version is 1.18.1-3.0.0.2, which should have this problem fixed. Can you test that version and see if the issue persists?

**Comment by Not-February** [comment]
Oops! Good catch, I didn't even notice I was a version behind.

That did indeed do the trick. I feel a bit silly now.

**Comment by TheIllusiveC4** [comment]
It's alright, no harm done. On the contrary, I really appreciate your initiative in reporting this because this particular issue went unaddressed for a long time with surprisingly nobody filing a proper bug report until I discovered it myself by chance. And since this is the first and only bug report for it, it will be useful to see the solution on record for others who may be encountering the issue.
