### ISSUE TITLE
Caelus 1.18.1 not working on 1.18.2 server

### ISSUE THREAD

**Issue by Zodzy** [TheIllusiveC4/Caelus#29]
### Minecraft Version

1.18.2

### What happened?

I am running 1.18.2 Forge server on Exaroton, and the Caelus 1.18.1-3.0.0.2 not working on it.

### How do you trigger this bug?

1.
2.
3.
...
I can't logging in the server

### Loader

Forge

### Loader Version

Forge - 40.1.0 (1.18.2)

### Mod Version

Caelus 1.18.1-3.0.0.2

**Comment by TheIllusiveC4** [comment]
You'll have to provide my information. Why can't you log into the server, what is the error that appears? Did you install the mod on both the client and server? Also, please provide the log files from that session so that I can identify the error from the logs.

**Comment by Zodzy** [comment]
I was wrong, it"s work, sorry
