### ISSUE TITLE
[Feature]: Using a keybinding, default 'v'

### ISSUE THREAD

**Issue by xuwuwudi** [TheIllusiveC4/Caelus#30]
### What is the new feature or improvement?

When it's off, the player cannot activate elytra flight at all. When it's on, the elytra flight can be activated as normal.
I hope this feature can return in 1.18.2.

**Comment by TheIllusiveC4** [comment]
For various reasons, I split that feature into its own mod:
https://www.curseforge.com/minecraft/mc-mods/elytra-utilities
