### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by butterflygirl30** [TheIllusiveC4/Caelus#32]
### Minecraft Version

1.19

### What happened?

game crashed when trying to start. I expected the game to start with only a few mods loaded

### How do you trigger this bug?

1. I installed origins, Origins++, Patchouli, and Pehkui. and your mod.
2. Game crashed- then I removed Origins++ due to an error
3. game still crashed
4. So I removed your mod game opened finally.
...

### Loader

Forge

### Loader Version

41.0.01

### Mod Version

1.19

### Relevant Log Outputs

https://pastebin.com/Q5aReHH0

**Comment by TheIllusiveC4** [comment]
The crash log is pointing to Origins as the cause. Have you tried loading it without Origins? If it still crashes, then give me the crash log without Origins installed.

**Comment by butterflygirl30** [comment]
ill try that but isnt origins needed?

**Comment by butterflygirl30** [comment]
i tried it, it worked, thank you. ignore previous question :)
