### ISSUE TITLE
It crashes me :/

### ISSUE THREAD

**Issue by MonkeyDLuffy0818** [TheIllusiveC4/Caelus#35]
### Minecraft Version

1.19.0

### What happened?

I'm using 1.19.2 and it crashes, And previous versions of caelus do not work for me

### How do you trigger this bug?

1. I put the mods
2. Run Minecraft
3. When starting it crashes

### Loader

Forge

### Loader Version

Forge - 43.2.8

### Mod Version

caelus-forge-1.19.4-3.0.0.10

**Comment by TheIllusiveC4** [comment]
You're using 1.19.2 but you're trying to install a 1.19.4 version of the mod. Please share the crash log if 1.19.2 versions of Caelus do not work in your 1.19.2 instance.
