### ISSUE TITLE
Forge version is too low, BUT cannot upgrade to a higher version due to it getting crashed because of minecraft version incompatiblity

### ISSUE THREAD

**Issue by Izanukiya** [TheIllusiveC4/Caelus#36]
### Minecraft Version

1.18.2

### What happened?

Basically when i try to launch i get the error screen saying that caelus requires a higher version of forge but I cant because the mods I have are limited to this version.

### How do you trigger this bug?

1. Add the mods
2. Run
3. Launch9
...

### Loader

Forge

### Loader Version

forge 39.12

### Mod Version

Caelus 1.18.1 3.0.0.2

**Comment by TheIllusiveC4** [comment]
Please share either your logs or a screenshot of the error saying that a requirement for Caelus is not met, because your version of Forge should already be fine for the latest version of Caelus on 1.18.
