### ISSUE TITLE
[Bug]: the elytra slot doesn't show

### ISSUE THREAD

**Issue by TsamT** [TheIllusiveC4/Caelus#40]
### Minecraft Version

1.20.4

### What happened?

when opening the curios slots, the elytra slot i doesn't show

### How do you trigger this bug?

1.open the curios slots

### Loader

Forge

### Loader Version

neoforge 190

### Mod Version

5.0.1

**Comment by TheIllusiveC4** [comment]
This mod doesn't have any Curios functionality, it's an API for elytra flight for developers.
