### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ThisMight** [TheIllusiveC4/Caelus#43]
### Minecraft Version

1.20.1

### What happened?

I was playing with the Feline origin, but the nocturnal vision did not appear.

Mods that affect rendering that were installed were Embeddium & Oculus (removing Oculus did not change the visuals)

### How do you trigger this bug?

1. play minecraft
2. join server with origins, embeddium and oculus installed
3. used my eyes
...

### Loader

Forge

### Loader Version

47.0.3

### Mod Version

1.20.1-1.10.0.9

**Comment by TheIllusiveC4** [comment]
I believe you may have reported this to the wrong repository, I think you're looking for Origins. This is the repository for the Caelus API mod.
