### ISSUE TITLE
Unexpected elytra and cape behaviour.

### ISSUE THREAD

**Issue by Krystian20857** [TheIllusiveC4/Caelus#5]
#### Versions (Be specific, do not write "latest"):
* Caelus: caelus-FORGE-1.15.2-2.0-beta2
* Forge: 1.15.2-31.2.0
#### Steps to Reproduce:
1. - Not required to fix this bug.
![2020-06-10_11 19 01](https://user-images.githubusercontent.com/34884977/84251698-ffa2b800-ab0d-11ea-91be-65518ad2d88e.png)

**Comment by TheIllusiveC4** [comment]
Fixed from https://github.com/TheIllusiveC4/Caelus/pull/6
