### ISSUE TITLE
Crash with latest 1.16.2 Forge builds (circa 33.0.57)

### ISSUE THREAD

**Issue by vico93** [TheIllusiveC4/Caelus#9]
#### Versions (Be specific, do not write "latest"):
* Caelus: caelus-forge-1.16.2-2.0.0.0
* Forge/Fabric: 1.16.2-33.0.57
#### Observed Behavior:
Seems like Caelus (or Curios Elytra) got wrecked in latest 1.16.2 Forge builds (trying on 33.0.57).

Removing the two mods (leaving only Curios API) makes the game run. But adding both Curious Elytra and Caelus API gives me a crash (without crash-report). [Here](https://hastebin.com/nakeneliqi.md)'s the `debug.log`

**Comment by TheIllusiveC4** [comment]
I can't reproduce this. Installing Curios 4.0.0.1, Caelus 2.0.0.0, and Curious Elytra 4.0.0.0 with Forge 33.0.57 allows the game to run perfectly fine. Also your hastebin is blank for me for whatever reason.

I'm not really sure what to follow up on in regards to your issue. Hmm, have you tried with only Caelus and seeing what happens?

**Comment by vico93** [comment]
Yeah, i think i was wrong in reporting it to you. My bad.

Seems like Forge had significant changes since build 22 (the last build my modpack boot normally), and after isolating mod by mod i realized it was caused by other two mods on the list.

Sorry for bother you...
